spring:
  profiles:
    include: "druid"
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.batis.demo.test.**entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mapper/mybatis-config.xml
